name: 'ansible-deploy'
description: 'This runs your ansible playbook in ansible container'
inputs:
  playbook:
    description: 'playbook name.'
    required: false
    default: "playbook.yaml"
  directory:
    description: 'path to the root directory where your ansible code lives'
    required: false
    default: '.'
  envvars:
    description: 'environment variables you need to pass to the playbook'
    required: false
  extvars:
    description: 'extra varibles you need to pass to the playbook'
    required: false
  ssh_key:
    description: 'the private ssh key you use to connect to remote node'
    required: false
  ssh_key_file_name:
    description: 'file name of your private ssh key. It will be put under ~/.ssh/'
    required: false
    default: "id_rsa"

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    ANSIBLE_DIRECTORY: ${{inputs.directory}}
    ANSIBLE_INVENTORY: "~/inventory" # let ansible read hosts from this directory
    ANSIBLE_ENVVARS: ${{inputs.envvars}}
    ANSIBLE_EXTVARS: ${{inputs.extvars}}
    ANSIBLE_PLAYBOOK: ${{inputs.playbook}}
    SSH_PRIVATE_KEY: ${{inputs.ssh_key}}
    SSH_PRIVATE_KEY_FILE: ${{inputs.ssh_key_file_name}}