name: main pipeline

on:
  push:
    paths-ignore:
      - image/**/*
      - "**/*.md"
      - LICENSE
  pull_request:
    paths-ignore:
      - image/**/*
      - "**/*.md"
      - LICENSE
    branches:
      - master
jobs:
    validate-envvars:
      runs-on: ubuntu-latest
      name: Test environment variables
      steps:
      - uses: actions/checkout@v2
      - name: run in ansible
        uses: ./
        with:
          directory: './tests/validate-envvars'
          envvars: |
            KEY:KEY_VALUE
            FRUIT:APPLE
            SECRET:309djlaljoiwl-fowkd

    validate-extvars:
      runs-on: ubuntu-latest
      name: Test extra variables
      steps:
      - uses: actions/checkout@v2
      - name: run in ansible
        uses: ./
        with:
          directory: './tests/validate-extvars'
          extvars: |
            package=tests/playbook.zip
            username=root
            os=linux
          playbook: ./playbook.yaml

    validate-ssh-key:
      runs-on: ubuntu-latest
      name: Test private ssh key setup
      steps:
      - uses: actions/checkout@v2
      - name: run in ansible
        uses: ./
        with:
          directory: './tests/validate-ssh-key'
          ssh_key: ${{ secrets.SAMPLE_SSH_KEY }}
          playbook: ./playbook.yaml

    validate-verbose:
      runs-on: ubuntu-latest
      name: Test verbosity
      steps:
      - uses: actions/checkout@v2
      - name: run in ansible
        uses: ./
        with:
          directory: './tests/validate-verbose'
          verbose: '4'

    setup-apache-2:
      runs-on: ubuntu-latest
      name: deploy apaache2 to local
      steps:
      - uses: actions/checkout@v2
      - name: Use ansible-deploy
        uses: ./
        with:
          directory: './tests/setup-apache-2'